# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'twitter-mood' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for twitter-mood
  pod 'Moya/RxSwift'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'SDWebImage', '~> 5.0'

  target 'twitter-moodTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
  end

  target 'twitter-moodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
